export const ActionTypes = {
  // user
  USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
  USER_LOADED: "USER_LOADED",
  UPDATE_USER: "UPDATE_USER",
  SIGN_OUT: "SIGN_OUT",
};
